version: "3.8"
services:
  mysql:
    container_name: mysql
    image: amitpurohit29/character-db:latest
    build: ./characters-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: charactersdb
    volumes:
      - type: volume
        source: characters-vol
        target: /var/lib/mysql
    networks:
      - "character-net"
  frontend:
    container_name: frontend 
    image: amitpurohit29/frontend:latest
    build: ./frontend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - published: 80
        target: 5000
        protocol: tcp
    networks:
      - "character-net"
  race:
    image: amitpurohit29/race:latest
    build: ./race
    networks:
      - "character-net"
  claas:
    image: amitpurohit29/claas:latest
    build: ./claas
    networks:
      - "character-net"
  weapon:
    image: amitpurohit29/weapon:latest
    build: ./weapon
    networks:
      - "character-net"
volumes:
  characters-vol:
networks:
  character-net: