- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  # tasks:
  # - name: create git dir
  #   file:
  #     state: directory
  #     path: /home/amit/Practical_Project
  # - name: clone repo
  #   git:
  #     repo: https://github.com/purohitamit/Practical_Project.git
  #     dest: /home/amit/Practical_Project
  #     clone: yes
  vars:
    docker_user: amit

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: webservers
  become: true
  roles:
  - nginx
  vars:
    docker_user: amit

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: amit
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: amit

